### ISSUE TITLE
working password on local but not working on main server

### ISSUE THREAD

**Issue by akang31** [dogeunderground/stronghold#3]

**Comment by anishathalye** [comment]
Hmm...

Could you email the password to team@hackmit.org?

**Comment by akang31** [comment]
it's the parenthesis that work/don't work it's weird

**Comment by anishathalye** [comment]
Oh dear. So sorry about that, it was fixed in the deploy but we forgot to push back here. Fixed now.

I checked, and since your password worked with the old implementation, we'll accept it. I've emailed you the code.

**Comment by akang31** [comment]
Oh, I already made a new one without those changes, but thank you anyway! Is the submit email button working on the command center?

**Comment by anishathalye** [comment]
Oh, cool.

And I'll check.
cc @katexyu

**Comment by katexyu** [comment]
Yes there's no feedback currently

New deploy will give you visual feedback
