### ISSUE TITLE
I have a password that passes validation but does not pass on the website

### ISSUE THREAD

**Issue by jamesjwu** [dogeunderground/stronghold#4]
The password has parenthesis in it, and copy pasting validation.js and running validator.validate on my end works. What could be the problem?

**Comment by anishathalye** [comment]
see #3

if you send it to team@hackmit.org and everything checks out, I'll send you the code.

(also not closing this so it'll stay in the open section and other people might see it)

**Comment by jamesjwu** [comment]
Sent!
