### ISSUE TITLE
Submission

### ISSUE THREAD

**Issue by AlexEKoren** [dogeunderground/stronghold#5]
So I got this correct and it accepted my answer and then asked for my e-mail, but then nothing happened. Is something else supposed to happen after that? Just want to make sure I can go to sleep and that my stuff has been recorded!

Thanks HackMIT and awesome puzzle!

**Comment by kimberli** [comment]
Yep, we gotchu :) Keep your eyes out for our feedback form, and we're excited to see you here in the fall!
